[package]
name = "high_d_graphing_calculator"
version = "0.1.0"
edition = "2021"

[dependencies]
gl = "*"
sdl2 = "*"
enum-ordinalize = "*"
nalgebra-glm = "*"
rusttype = { version = "0.9.3", features = ["gpu_cache"] }